### ISSUE TITLE
Error "The handle is already open" ﻿

### ISSUE THREAD

**Issue by wesleywerner** [wesleywerner/dmon#2]
```
C:\doom\dmon>dmon znato.wad map01 -u
Traceback (most recent call last):
  File "C:\doom\dmon\\dmon.py", line 657, in <module>
    main()
  File "C:\doom\dmon\\dmon.py", line 651, in main
    process_wad(options)
  File "C:\doom\dmon\\dmon.py", line 404, in process_wad
    wad_data = extract_statistics(options)
  File "C:\doom\dmon\\dmon.py", line 161, in extract_statistics
    from omg import omg
  File "C:\doom\dmon\omg\__init__.py", line 30, in <module>
    from omg.wadio import *
  File "C:\doom\dmon\omg\wadio.py", line 81
    raise IOError, "The handle is already open"
```

**Comment by wesleywerner** [comment]
Issue is resolved with upgrade of Omgifol
